title:              JH
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             JH
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   JH
github_username:    JH
facebook_username:  JH
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
